### ISSUE TITLE
Master Issue Checklist (Auto-updated)

### ISSUE THREAD

**Issue by jaivardhankapoor** [mackelab/labproject#6]
### Unlabeled
- [x] #24 Scaling - added standard error in plots - Assignees: 
- [ ] #23 Metrics decorator - Assignees: manuelgloeckler
- [ ] #22 Colour dictionary for metrics - Assignees: a-darcher
- [x] #21 Make Toy2D a distribution - Assignees: 
- [ ] #20 How do different distance metrics scale with dimensionality? - Assignees: coschroeder
- [ ] #19 How do different distance metrics scale with sample size? - Assignees: augustes
- [x] #18 Add optimal c2st - Assignees: 
- [ ] #16 Interactive notebook for uploading and evaluating own data - Assignees: 
- [x] #15 Additional Github Action for non-main branches - Assignees: 
- [x] #14 Updated workflows - Assignees: 
- [x] #13 Nicer docs, Will try to host it on Github Pages - Assignees: 
- [x] #12 Adding the configs, per run and seeding and so one - Assignees: 
- [x] #3 API documentation with mkdocs - Assignees: jaivardhankapoor

### code org
- [x] #17 Add results folder and methods to save python objects returned by experiment classes - Assignees: jaivardhankapoor, manuelgloeckler
- [x] #4 Meeting notes - Assignees: jaivardhankapoor, Matthijspals, manuelgloeckler
- [x] #2 Explanatory slides for Code Org - Assignees: jaivardhankapoor, Matthijspals, manuelgloeckler
- [ ] #1 Set up fileserver - Assignees: jaivardhankapoor

### writing
- [ ] #11 Applications - Assignees: a-darcher
- [ ] #10 Introduction to generative models - Assignees: 
- [ ] #9 FID and friends - Assignees: 
- [ ] #8 Embeddings / C2ST - Assignees: 
- [ ] #7 Slicing / Wasserstein - Assignees: gmoss13
- [ ] #5 MMD / Kernel methods - Assignees: Matthijspals
